server:
  port: 8080

dify:
  url: http://localhost:80 # 服务端地址
  server:
    email: admin@admin.com
    password: admin123456
  dataset:
    api-key: dataset-RElQVTSsCQlp0F91hGpZrLBn # 知识库 api-key
  client-config:
    logging: true
logging:
  level:
    root: ERROR
    io.github.guoshiqiufeng.dify: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
